# Site settings
title: Leon's Blog
email: leon_e@163.com
description: "Embedded System, Linux, Python & Ruby"
github_username: yixiaoyang
#baseurl: "http://yixiaoyang.github.io"
baseurl:  ''
# About/contact
author:
  name:              Leon
  url:               ''
  email:             leon_e@163.com
  
# Build settings
markdown: kramdown
kramdown:
   input: GFM
   extensions:
      - autolink
      - footnotes
      - smart
   auto_ids: false
   use syntax_highlighter: coderay
   enable_coderay: false
   coderay:
      coderay_wrap:              div
      coderay_line_numbers:      inline
      coderay_line_number_start: 1
      coderay_tab_width:         4
      coderay_bold_every:        10
      coderay_css:               style
#markdown: redcarpet
#redcarpet:
#   extensions: ["fenced_code_blocks", "tables", "highlight", "with_toc_data", "strikethrough", "with_toc_data", "autolink"]


permalink: /:year/:month/:day/:title/

highlighter: rouge

